drop table if exists Person CASCADE;
drop table if exists Tax CASCADE;
drop schema IF EXISTS report;

Create table Tax(
ID int PRIMARY KEY,
income numeric(12,2)
);

create table Person(
ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name text,
last_name text,
TAX_ID int REFERENCES Tax(ID)
);


INSERT INTO Tax(ID, income) VALUES
(482, 123000.33), (19, 12.33),(7, 1503), (364, 123000.33), (62, 12.33),(815, 1503), 
(3, 13000.33), (936, 125.33),(57, 14503), (408, 3123000.33), (16, 1244.33),(793, 15203),
(335, 48250.10), (9, 72100), (927, 3850.75), (21, 91400.20), (549, 26780.50), (873, 158300),
(40, 64520.45), (158, 8900), (1, 43210.99), (394, 117650.30), (628, 5230.80), (91, 38900),
(283, 205400.15), (537, 67300.60), (84, 1999.99), (179, 84750), (5, 29640.25), (735, 136200.40),
(318, 45000), (60, 7815.35), (951, 99870.10), (227, 52360.70), (8, 310500), (869, 18430.55),
(136, 76900.25), (47, 4120), (712, 61275.80), (358, 143800.05), (64, 33300), (2, 88150.65),
(184, 12675.40), (516, 245900), (85, 57430.20), (290, 9360.90), (437, 71800), (76, 166250.35),
(105, 40560.75), (649, 2875.10), (4, 95340), (917, 23180.60), (254, 128700.45), (58, 69015),
(836, 15840.30), (173, 47725.85), (46, 188300), (725, 36410.20), (314, 5670), (6, 102950.55),
(948, 58240.40), (26, 27390), (593, 81460.15), (812, 11025.70), (14, 139500), (476, 44890.35),
(739, 6340.95), (38, 97210), (615, 31875.60), (904, 174400.25), (237, 53600), (568, 20145.80),
(841, 86730.45), (193, 3290), (42, 119840.10), (759, 62580.30), (371, 14960), (99, 79215.65),
(682, 228750), (245, 39480.55), (13, 8125.20), (507, 104630), (866, 49970.85), (31, 25310.40),
(154, 67890), (720, 152275.15), (67, 34615.90), (398, 7480), (971, 91055.35), (125, 43360.70),
(53, 211900), (604, 16725.25), (288, 73540.60), (88, 5915), (443, 125480.40), (777, 55505.75),
(35, 28840), (519, 83170.20), (202, 10450.95), (690, 197600);


INSERT INTO person (name, last_name, tax_id) VALUES
('James', 'Smith', 482),('Mary', 'Johnson', 19),('John', 'Williams', 7),
('Patricia', 'Brown', 364),('Robert', 'Jones', 62),('Jennifer', 'Garcia', 815),
('Michael', 'Miller', 3),('Linda', 'Davis', 936),('William', 'Rodriguez', 57),
('Elizabeth', 'Martinez', 408),('David', 'Hernandez', 16),('Barbara', 'Lopez', 793),
('Richard', 'Gonzalez', 335),('Susan', 'Wilson', 9),('Joseph', 'Anderson', 927),
('Jessica', 'Thomas', 21),('Thomas', 'Taylor', 549),('Sarah', 'Moore', 873),
('Charles', 'Jackson', 40),('Karen', 'Martin', 158),('Christopher', 'Lee', 1),
('Nancy', 'Perez', 394),('Daniel', 'Thompson', 628),('Lisa', 'White', 91),
('Matthew', 'Harris', 283),('Betty', 'Sanchez', 537),('Anthony', 'Clark', 84),
('Margaret', 'Ramirez', 179),('Mark', 'Lewis', 5),('Sandra', 'Robinson', 735),
('Donald', 'Walker', 318),('Ashley', 'Young', 60),('Steven', 'Allen', 951),
('Kimberly', 'King', 227),('Paul', 'Wright', 8),('Emily', 'Scott', 869),
('Andrew', 'Torres', 136),('Donna', 'Nguyen', 47),('Joshua', 'Hill', 712),
('Michelle', 'Flores', 358),('Kenneth', 'Green', 64),('Carol', 'Adams', 2),
('Kevin', 'Nelson', 184),('Amanda', 'Baker', 516),('Brian', 'Hall', 85),
('Dorothy', 'Rivera', 290),('George', 'Campbell', 437),('Melissa', 'Mitchell', 76),
('Timothy', 'Carter', 105),('Deborah', 'Roberts', 649),('Ronald', 'Gomez', 4),
('Stephanie', 'Phillips', 917),('Edward', 'Evans', 254),('Rebecca', 'Turner', 58),
('Jason', 'Diaz', 836),('Sharon', 'Parker', 173),('Jeffrey', 'Cruz', 46),
('Laura', 'Edwards', 725),('Ryan', 'Collins', 314),('Cynthia', 'Reyes', 6),
('Jacob', 'Stewart', 948),('Kathleen', 'Morris', 26),('Gary', 'Morales', 593),
('Amy', 'Murphy', 812),('Nicholas', 'Cook', 14),('Angela', 'Rogers', 476),
('Eric', 'Gutierrez', 739),('Shirley', 'Ortiz', 38),('Jonathan', 'Morgan', 615),
('Anna', 'Cooper', 904),('Stephen', 'Peterson', 237),('Brenda', 'Bailey', 568),
('Larry', 'Reed', 841),('Pamela', 'Kelly', 193),('Justin', 'Howard', 42),
('Emma', 'Ramos', 759),('Scott', 'Kim', 371),('Nicole', 'Cox', 99),
('Brandon', 'Ward', 682),('Helen', 'Richardson', 245),('Benjamin', 'Watson', 13),
('Samantha', 'Brooks', 507),('Samuel', 'Chavez', 866),('Katherine', 'Wood', 31),
('Gregory', 'James', 154),('Christine', 'Bennett', 720),('Frank', 'Gray', 67),
('Debra', 'Mendoza', 398),('Alexander', 'Ruiz', 971),('Rachel', 'Hughes', 125),
('Raymond', 'Price', 53),('Carolyn', 'Alvarez', 604),('Patrick', 'Castillo', 288),
('Janet', 'Sanders', 88),('Jack', 'Patel', 443),('Maria', 'Myers', 777),
('Dennis', 'Long', 35),('Catherine', 'Ross', 519),('Jerry', 'Foster', 202),
('Heather', 'Jimenez', 690);

